version: '3.8'

services:
  recipe-creator:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - OLLAMA_API_URL=http://localhost:11434
    volumes:
      - ollama-models:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ollama-models:
    # This volume stores the Ollama models to avoid re-downloading them each time 